export const GLOBAL_VAR_NAME = 'SIMPLE_WINDOW_MANAGER';

export const LIB_PREFIX = 'ElectronSimpleWindowManager/';

export const OPEN_WINDOW = LIB_PREFIX + 'OPEN_WINDOW';
export const CLOSE_WINDOW = LIB_PREFIX + 'CLOSE_WINDOW';
export const SHOW_WINDOW = LIB_PREFIX + 'SHOW_WINDOW';
export const HIDE_WINDOW = LIB_PREFIX + 'HIDE_WINDOW';
export const OPEN_DEVTOOLS = LIB_PREFIX + 'OPEN_DEVTOOLS';
export const CLOSE_DEVTOOLS = LIB_PREFIX + 'CLOSE_DEVTOOLS';
export const SET_BOUNDS = LIB_PREFIX + 'SET_BOUNDS';